### ISSUE TITLE
Premium and private plugins

### ISSUE THREAD

**Issue by Pushplaybang** [soberwp/themer#2]
Is it possible to use this with private or premioum plugins? Either hosted locally or on  a private repo?

**Comment by darrenjacoby** [comment]
I don't think the tgmpa class supports this use this. Bundle just implements an easier interface for using that class.

**Comment by Pushplaybang** [comment]
@darrenjacoby  - Hey there, thanks for the quick response.

having a look at TGMPA .it seems the source attribute can be used for bundled plugins (not ideal, but will still be a better way to manage premium plugins for my woocommerce store),

from the [docs](http://tgmpluginactivation.com/configuration/)

source | string | v2.0.0 | The source of the plugin.This parameter is required if the plugin you are referencing is not from the WordPress Plugin Repository.You can reference either bundled plugins or plugins elsewhere on the internet from this parameter.For bundled plugins, this should be the path to the .zip file. For external plugins, the direct url to the .zip file.
-- | -- | -- | --

will give this a go.
