### ISSUE TITLE
Composer?

### ISSUE THREAD

**Issue by alicam** [soberwp/themer#3]
Got this on installation:

"Your requirements could not be resolved to an installable set of packages."

Issue with  hassankhan/config dependency.

Can you advise?

A

**Comment by darrenjacoby** [comment]
@alicam are you using it with Models? There may be a dependency conflict. If this is the case, I will be able to upgrade later which should resolve.

**Comment by alicam** [comment]
Yes. And models did install ok.

**Comment by darrenjacoby** [comment]
Yea, we just need to bump the version number on composer.json here to `"hassankhan/config": "^1.0"`

**Comment by alicam** [comment]
Not super urgent, but I'll need it soon :)

**Comment by darrenjacoby** [comment]
I have just updated `composer.json`. Give 1.0.2 a go and let me know if it works.
